version: '3.3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm_${APP_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    networks: 
      - backend

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx_${APP_NAME}
    restart: unless-stopped
    tty: true
    ports: 
      - 1002:80
      - 2002:443
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

networks:
  backend:
    driver: bridge
